### PR TITLE
Various fixes and enhancements

### PR DESCRIPTION
**Pull request by db3000**
Replacement for https://github.com/peap/alexa-roku/pull/1

### CODE REVIEW

**Comment by peap** [comment]
Thanks again! I'm going to let `AMAZON_APPLICATION_ID` and `ROKU_ADDRESS` be environment variables, and add a few utterances for RokuSearchIntent. Will merge in a sec.

**Comment by peap** [comment]
OK, so it's merged, but turns out my search option is only two items below home, not five. I think there might be something here that'll help, though: https://sdkdocs.roku.com/display/sdkdoc/External+Control+Guide#ExternalControlGuide-searchExamples - I did try having it press the search button, but that didn't do anything on my Roku 3.

Edit: once I got to the search screen, however, the typing worked great! I love it.

**Comment by db3000** [comment]
D'oh sorry about that. I actually tried all the '/search' examples and endpoints but I couldn't make them do anything.

The extra items on my menu seem to be "Movie Store", "TV Store" and "News", which can be toggled on and off using Settings -> Home Screen. I have an idea though, these also appear as apps in the response to '/query/apps', and they seem to have a special type of "menu", for example:

```
$ curl http://roku-bedroom:8060/query/apps
<?xml version="1.0" encoding="UTF-8" ?>
<apps>
        <app id="31012" type="menu" version="1.6.8">Movie Store and TV Store</app>
        <app id="31863" type="menu" version="1.2.6">Roku Home News</app>
        <app id="12" type="appl" version="4.2.132">Netflix</app>
        <app id="13" type="appl" version="6.1.0">Amazon Video</app>
...
```

Maybe the search intent could get the list of apps first, and add one down press for each 'type="menu"' it finds (with an extra one for Movie Store and TV Store)? I'll see if I can try that out at some point today.

Also, for the config, would be nice if you could pass in a config file to app.app.

**Comment by db3000** [comment]
Oh wait, the '/search' endpoint does work, I just needed to update the software on my Roku. Now that it's at version 7.5 it works perfectly, the '/search' endpoint is the way to go for sure.

**Comment by peap** [comment]
Awesome, thanks for trying that out. I'll take a look at #3 in a few.

Interestingly, my Roku 3 also has software version 7.5.0, but none of the `menu` type channels show up in /query/apps. Maybe because I need to enable them? Oh well, glad the /search endpoint works!

**Comment by db3000** [comment]
Yeah, they are optionally enabled, and don't appear in the list if you have then off. The option is under Settings -> Home Screen.

**Pull request merged**
