### PR TITLE
Various fixes and enhancements

### PR DESCRIPTION
**Pull request by db3000**
Hey, thanks for your Roku Alexa skill, it's definitely one of the more full featured ones and works nicely behind nginx.

Just wanted to submit a few changes I made while getting it working, in particular I really wanted to be able to do arbitrary searches easily, now you can say "open roku search" and "enter kung fury". Also, I needed a non-SSDP option, as SSDP is impossible through a firewall (it uses an arbitrary port).

Let me know what you think, thanks.

```
Changes:
* Add 'RokuSearch' intent for launching main Roku search screen
* Add 'Literal' intent for typing arbitrary text
* Allow static IP setting for Roku (SSDP is impossible through firewalls)
* Normalize set of buttons in ASK and code, add 'pause' and 'stop'
* Remove personally identifying information
```

### CODE REVIEW

**Comment by db3000** [comment]
Needs a fix, will reopen

**Comment by peap** [comment]
Awesome, thanks! I like this. Looking forward to the changes.

**Comment by db3000** [comment]
Sure thing, test it out if you can. It works on my Roku 2 and Roku 3.

Turns out I needed an extra sleep in the search intent and the "LITERAL_TEXT" type has to have a single word option. Reopening pull.

**Comment by db3000** [comment]
Replaced by https://github.com/peap/alexa-roku/pull/2

**Pull request closed without merging**
